### ISSUE TITLE
Make training pipeline extensible

### ISSUE THREAD

**Issue by logan-connolly** [logan-connolly/aita#20]
### Problem

The current implementation of `nlp` train pipeline is heavily coupled to `spacy`, which makes it hard to extend the code to support other libraries.

### Goal

The goal is to abstract out the train pipeline into a generic workflow starting with reading in data from the API to exporting the trained model. Once this is defined, any external library or strategy just needs to adhere to the defined interface.

### Todos

- [ ] Define the generic workflow of the train pipeline (inputs/outputs);
- [ ] Remove spacy specific code from application logic;
- [ ] Refactor current implementation so that the same result is achieved, but with `spacy` specific code being injected into the train pipeline as a valid strategy.
